{% set data = load_setup_py_data() %}

package:
  name: {{ data['name'] }}
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python -m pip install --no-deps --ignore-installed .
  string: np{{CONDA_NPY}}py{{CONDA_PY}}_{{PKG_BUILDNUM}}_h{{PKG_HASH}}_g{{GIT_FULL_HASH[:7]}}

requirements:
  host:
    - python
    - pip
  run:
    - python >= 3.7
    - jupyter
    - pandas
    - plotly
    - psutil
    - sphinx
    - rise

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - pytest tests

about:
  home: https://github.com/fynnbe/advanced_python_2019_EBI
  summary: "course at EBI on git and GitHub"
  license: {{ setup_py.get('license') }}
  license_file: LICENSE
